sudo: required
services:
  - docker

before_install:
  - docker build -t sunnyrajput/docker-react-app -f Dockerfile.dev .

script:
  - docker run sunnyrajput/docker-react-app npm run test -- --coverage
